baseUrl: 'https://signalskew.com'
title: SignalSkew
author: Chris Miller
theme: signalskew.com-theme-distillpub
canonifyurls: true
enableInlineShortcodes: true
taxonomies:
  category: categories
  series: series
  tag: tags
params:
  #logo: /images/signalskew_logo.svg
  description: SignalSkew blog
  keywords:
    - electronics
    - pcbs
    - design
  sourcePrefix: 'https://github.com/signalskew/signalskew.com'
  color: '#0f2e3d'
  social:
    - class: fab fa-github
      url: 'https://github.com/signalskew'
    - class: fab fa-twitter
      url: 'https://twitter.com/signalskew'
menu:
  main:
    - identifier: about
      name: About
      title: About
      url: /about
      weight: -10
    - identifier: option1
      name: Option 1
      title: Option 1
      url: /opt1
      weight: -10
    - identifier: option2
      name: Option 2
      title: Option 2
      url: /opt2
      weight: -10