baseUrl: 'https://signalskew.com'
title: SignalSkew
author: Chris Miller
theme: signalskew-theme
canonifyurls: true
enableInlineShortcodes: true
taxonomies:
  category: categories
  series: series
  tag: tags
params:
  #logo: /images/signalskew_logo.svg
  description: SignalSkew blog
  theme_color: '#0f2e3d'
  #header_metadata: '<a style="display: none;" rel="me" href="https://leds.social/@signalskew">Mastodon verification</a>'
  keywords:
    - electronics
    - pcbs
    - design
    - CNC
    - embedded
  sourcePrefix: 'https://github.com/signalskew/signalskew.com'
  social:
    - class: fab fa-mastodon
      url: 'https://leds.social/@signalskew'
      alt: 'Connect on Mastodon'
    - class: fab fa-twitter
      url: 'https://twitter.com/signalskew'
      alt: 'Connect on Twitter'
    - class: fab fa-github
      url: 'https://github.com/signalskew'
      alt: 'My GitHub profile'
menu:
  main:
    - identifier: about
      name: About
      title: About
      url: /about
      weight: -10
    - identifier: projects
      name: Projects
      title: Projects
      url: /proj
      weight: -8
