baseUrl: 'https://signalskew.com'
title: SignalSkew
author: Chris Miller
theme: signalskew.com-theme-distillpub
canonifyurls: true
enableInlineShortcodes: true
taxonomies:
  category: categories
  series: series
  tag: tags
params:
  #logo: /images/signalskew_logo.svg
  description: SignalSkew blog
  color: '#0f2e3d'
  keywords:
    - electronics
    - pcbs
    - design
    - CNC
    - embedded
  sourcePrefix: 'https://github.com/signalskew/signalskew.com'
  social:
    - class: fab fa-github
      url: 'https://github.com/signalskew'
    - class: fab fa-twitter
      url: 'https://twitter.com/signalskew'
menu:
  main:
    - identifier: about
      name: About
      title: About
      url: /about
      weight: -10
    - identifier: projects
      name: Projects
      title: Projects
      url: /proj
      weight: -8