baseUrl = "https://pcb.fun"
title = "SignalSkew"
author = "Chris Miller"
canonifyurls = true
theme = "pcb-fun-theme-distillpub"


[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'


[params]
  description = "pcb.fun blog"
  keywords = ["electronics", "pcbs", "design"]
  sourcePrefix = "https://github.com/signalskew/pcb-fun"

  color = "#0f2e3d"
  custom_css = ["css/custom.css"]
  dark_mode_css = ["css/darkmode.css"]
  #custom_js = ["js/custom.js"]
  dark_mode_js = ["js/darkmode.js"]

  [[params.social]]
  class = "fab fa-github"
  url = "https://github.com/signalskew"

  [[params.social]]
  class = "fab fa-twitter"
  url = "https://twitter.com/signalskew"

[menu]

  [[menu.main]]
  identifier = "about"
  name = "About"
  title = "about"
  url = "/about"
  weight = -10

