baseUrl: 'https://signalskew.com'
title: SignalSkew
author: Chris Miller
canonifyurls: true
theme: signalskew.com-theme-distillpub
taxonomies:
  category: categories
  series: series
  tag: tags
params:
  description: SignalSkew blog
  keywords:
    - electronics
    - pcbs
    - design
  sourcePrefix: 'https://github.com/signalskew/signalskew.com'
  color: '#0f2e3d'
  custom_css:
    - css/custom.css
  dark_mode_css:
    - css/darkmode.css
  dark_mode_js:
    - js/darkmode.js
  social:
    - class: fab fa-github
      url: 'https://github.com/signalskew'
    - class: fab fa-twitter
      url: 'https://twitter.com/signalskew'
menu:
  main:
    - identifier: about
      name: About
      title: about
      url: /about
      weight: -10