baseUrl: 'https://signalskew.com'
title: Signalskew
author: Chris Miller
theme: signalskew.com-theme-distillpub
canonifyurls: true
enableInlineShortcodes: true
taxonomies:
  category: categories
  series: series
  tag: tags
params:
  description: SignalSkew blog
  keywords:
    - electronics
    - pcbs
    - design
  sourcePrefix: 'https://github.com/signalskew/signalskew.com'
  color: '#0f2e3d'
  social:
    - class: fab fa-github
      url: 'https://github.com/signalskew'
    - class: fab fa-twitter
      url: 'https://twitter.com/signalskew'
menu:
  main:
    - identifier: about
      name: About
      title: about
      url: /about
      weight: -10