baseUrl: 'https://signalskew.com'
title: SignalSkew
author: Chris Miller
theme: signalskew-theme
canonifyurls: true
enableInlineShortcodes: true
taxonomies:
  category: categories
  series: series
  tag: tags
params:
  #logo: /images/signalskew_logo.svg
  description: SignalSkew blog
  theme_color: '#0f2e3d'
  dark_mode_feature: true
  #header_metadata: 'Put e.g. Mastodon verification link here (may be deleted after verification)'
  social_in_menu: false
  rss_in_menu: true

  keywords:
    - electronics
    - pcbs
    - design
    - CNC
    - embedded
  sourcePrefix: 'https://github.com/signalskew/signalskew.com'
  social:
    - class: fab fa-mastodon
      url: 'https://leds.social/@signalskew'
      alt: 'Connect on Mastodon'
    - class: fab fa-twitter
      url: 'https://twitter.com/signalskew'
      alt: 'Connect on Twitter'
    - class: fab fa-github
      url: 'https://github.com/signalskew'
      alt: 'My GitHub profile'
menu:
  main:
    - name: Projects
      title: Projects
      url: /proj
      weight: 1
    - name: About
      title: About
      url: /about
      weight: 10
